### ISSUE TITLE
如何单独替换粗体、等宽等样式使用的字体？

### ISSUE THREAD

**Issue by tty7tyil** [ysc3839/FontMod#50]
你好，我没有配置 `yaml` 文件的经验，可否指导一下要达成下面的效果应如何写替换规则？

- 消息中的普通文本为字体 `a.otf`
- 等宽样式为字体 `b.otf`
- 粗体样式为字体 `c.otf`（原本已经由于未知原因粗体没有视觉差异，故想独立指定粗体字体文件）

目前我的配置如下，仅能替换普通文本字体：

```
  MS UI Gothic: # Japanese fallback font
    replace: SourceHanSansCN-ExtraLight.otf
    <<: *style
```

**Comment by tty7tyil** [comment]
嗯……我发现了应该写字体名称而不是文件名。但是为什么不正确地使用了文件名仍然能够正确地影响到字体使得本来的日文字形变回了中文字形？

**Comment by ysc3839** [comment]
这方面我之前研究过，某些 Qt 程序在使用 fallback font 的时候不会带上粗体等信息，同时该项目目前只支持按照字体名称匹配，所以无法实现。
对于 Telegram 这种原始字体名称中就包含粗体信息的，可以实现，不过是中文和英文全都替换，不能实现仅替换中文。想要英文部分使用 OpenSans，中文部分使用自己的字体的话，需要自己使用工具把这两部分合成为一个新的字体。

**Comment by tty7tyil** [comment]
> 
> 
> 这方面我之前研究过，某些 Qt 程序在使用 fallback font 的时候不会带上粗体等信息，同时该项目目前只支持按照字体名称匹配，所以无法实现。
> 对于 Telegram 这种原始字体名称中就包含粗体信息的，可以实现，不过是中文和英文全都替换，不能实现仅替换中文。想要英文部分使用 OpenSans，中文部分使用自己的字体的话，需要自己使用工具把这两部分合成为一个新的字体。

谢谢。忘记注明了我是在替换 Telegram。  
那么配置文件类似这个样子，原字体名称可从 log 获得？

```
  ori font: # Japanese fallback font
    replace: some font
    <<: *style
  ori font bold varient: # Japanese fallback font
    replace: another font
    <<: *style
```

为什么说只能全部替换呢？不同语言粗体样式应该是用的不同**原**字体吧？

**Comment by tty7tyil** [comment]
> 
> 
> 这方面我之前研究过，某些 Qt 程序在使用 fallback font 的时候不会带上粗体等信息，同时该项目目前只支持按照字体名称匹配，所以无法实现。
> 对于 Telegram 这种原始字体名称中就包含粗体信息的，可以实现，不过是中文和英文全都替换，不能实现仅替换中文。想要英文部分使用 OpenSans，中文部分使用自己的字体的话，需要自己使用工具把这两部分合成为一个新的字体。

不能实现仅替换中文是因为中文字形本来就是 fallback 出来的，不存在一个「ZH Bold」、「ZH Mono」这样的字体名可供替换为自定义字体，对吗？

而可行的替换方法只有替换掉原始字体变种如「Open Sans Bold」、「Consolas」为自定义字体，但这样也就替换掉了所有字体包括英文，对吗？

**Comment by ysc3839** [comment]
原始字体可以通过 log 获得，issue 里面也可以找到，大概是 `DAOpenSansRegular` 这样的。
全部替换指的是中英文全部替换，可以按照不同的粗体来替换。

**Comment by tty7tyil** [comment]
成功替换了，替换部分如下：

``` yaml
fonts:
  # 替换默认字体 Open Sans 与默认等宽字体 Consolas。
  # 被替换的原字体以 log 为准。
  # 用于替换的字体名称以 Windows 显示为准（预览字体文件），但是各种变体名称照常
  # 添加（Regular 除外）。总之多种写法试一下，**要注意即使使用了不正确的名称，软
  # 件内的字形仍可能有变化，但与所指定字形会有差异**。
  DAOpenSansRegular:
    replace: 更纱黑体 SC
    <<: *style
  DAOpenSansRegularItalic:
    replace: 更纱黑体 SC Italic
    <<: *style
  DAOpenSansSemibold:
    replace: 更纱黑体 SC Semibold
    <<: *style
  DAOpenSansSemiboldItalic:
    replace: 更纱黑体 SC Semibold Italic
    <<: *style
  DAOpenSansBold:
    replace: 更纱黑体 SC Bold
    <<: *style
  DAOpenSansBoldItalic:
    replace: 更纱黑体 SC Bold Italic
    <<: *style
  Consolas:
    replace: 等距更纱黑体 T SC
    <<: *style
```

效果如图：

![image](https://user-images.githubusercontent.com/13289283/74085817-fea63f00-4ab7-11ea-9fea-992f2ca5bb22.png)
