### ISSUE TITLE
您好，现在英文字体比中文小，应该如何修改呢？

### ISSUE THREAD

**Issue by Hades-Shaw** [ysc3839/FontMod#54]
您好，我现在已经成功修改了中文字体和大小，但是现在英文字体比中文小，应该如何修改英文字体大小呢？

**Comment by ysc3839** [comment]
把字体“替换”成它本身，同时修改大小。
比如英文字体名为 `Arial`
```
fonts:
  Arial:
    replace: Arial
    size: 40
```
