### ISSUE TITLE
how to set 'key' ?

### ISSUE THREAD

**Issue by hsungha** [ysc3839/FontMod#61]
> If you want replace only CJK fonts and keep English font, you need to set key to CJK fallback font. This font may be different in different language environments. (For example in Chinese simplified environment is SimSun), you can use debug mode to find corresponding font.

i don't know how to set key... sorry noob question..

**Comment by ysc3839** [comment]
"key" is the key of yaml objects. https://en.wikipedia.org/wiki/YAML#Basic_components
For example:
```
foo:
  bar: baz
```
`foo` and `bar` are keys.

**Comment by hsungha** [comment]
> you need to set key to CJK fallback font. 

i want keep english default font. but tutorial is not shown how to set key.
please example..

**Comment by ysc3839** [comment]
```
fonts:
  SimSun: &zh-cn-font # Chinese (Simplified) fallback font
    replace: Microsoft YaHei
    <<: *style
```
Here `SimSun` is the "key".

**Comment by hibiyasleep** [comment]
pardon for the interruption, before of all, sorry for poor english - I don't read/or/write it often. 

anyway, I'm also getting little confusion on it, set key of *what*?

As long as I understood, fontname said in `(object key)` is the font that should be replaced, and the value of `(object key).replace` is the destination font; so when I do *set key to CJK fallback font*, results should be like below;

```yaml
fonts:
  Gulim:
    replace: 맑은 고딕
  Gulim: # guide said, set key to (ry), but key of where?
    replace: Roboto
```

but... this will result in key conflict. 

---

or, may I interpret `set key to CJK fallback font` as `replace destination font to english-only font`?

let's make an example, if user wants to replace `Gulim` to `Malgun Gothic`, but keep english glyphs in `Roboto` (which only supports latin characters), then is this what README meant?:

```yaml
fonts:
  Gulim: # (from)
    replace: 맑은 고딕 # (to)
    <<: *style
  '맑은 고딕': # (from)
    replace: Roboto #(to)
```
