### ISSUE TITLE
無法替換為特定字型

### ISSUE THREAD

**Issue by bestpika** [ysc3839/FontMod#79]
我試著用 v3、v3.1 將 Telegram 的字型替換為 <https://github.com/ButTaiwan/gensen-font/releases/tag/v1.501> 系列時發現沒辦法正確替換
但是在 2.1 時，同樣的設定檔是可以運作的
```yaml
# FontMod
fonts:
  DAOpenSans:
    replace: 源泉圓體 L
  DAOpenSansItalic:
    replace: 源泉圓體 L
  DAOpenSansRegular:
    replace: 源泉圓體 R
  DAOpenSansRegularItalic:
    replace: 源泉圓體 R
  DAOpenSansSemibold:
    replace: 源泉圓體 M
  DAOpenSansSemiboldItalic:
    replace: 源泉圓體 M
  DAOpenSansBold:
    replace: 源泉圓體 B
  DAOpenSansBoldItalic:
    replace: 源泉圓體 B
  Consolas:
    replace: Fira Code Medium
# fallback
fixGSOFont: true
debug: false
```
